# Generated by Django 3.1.5 on 2021-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210325_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_report_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
