# Generated by Django 3.1.5 on 2021-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_patient_report_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_report_raw',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
